services:
  - type: web
    name: hackrx-document-api
    runtime: python3
    buildCommand: pip install -r render-requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: hackrx-documents
      - key: PINECONE_ENV
        value: us-east-1-aws